#! /bin/bash
gpg-connect-agent "scd serialno" "learn --force" /bye

keyno=$(ykman info | grep "Serial number" | awk '{print $3}')

sed -i s/andrew_on_titan_for_thor_using_sk_[[:digit:]]*/andrew_on_titan_for_thor_using_sk_$keyno/ ~/.ssh/config
sed -i s/andrew_on_thor_for_titan_using_sk_[[:digit:]]*/andrew_on_thor_for_titan_using_sk_$keyno/ ~/.ssh/config

sed -i s/andrew_on_titan_for_github_using_sk_[[:digit:]]*/andrew_on_titan_for_github_using_sk_$keyno/ ~/.ssh/config
sed -i s/andrew_on_thor_for_github_using_sk_[[:digit:]]*/andrew_on_thor_for_github_using_sk_$keyno/ ~/.ssh/config
