#! /bin/bash
TMPFILE=$(mktemp)
trap 'rm "$TMPFILE"' EXIT

export DOPPLER_PROJECT="development"
export DOPPLER_CONFIG="github"

GITHUB_TOKEN=$(doppler secrets get GITHUB_TOKEN_PUBLIC_REPOS --plain)

echo "[keys]" >$TMPFILE
echo "github = \"$GITHUB_TOKEN\"" >>$TMPFILE

nvchecker -c /etc/nvchecker/config_file.toml --logging warning --keyfile $TMPFILE
nvcmp -c /etc/nvchecker/config_file.toml
